### Zadanie 1
Wykonaj następujące polecenia za pomocą biblioteki NumPy.

Importuj bibliotekę NumPy

Stwórz tablicę zawierającą 10 elementów o wartości 0

In [12]:
######################################################################################

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Stwórz tablicę zawierającą 10 elementów o wartości 1

In [4]:
######################################################################################

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Stwórz tablicę zawierającą 10 elementów o wartości 2

In [5]:
######################################################################################

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Stwórz tablicę zawierającą elementy z zakresu od 20 do 40

In [9]:
######################################################################################

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

Stwórz tablicę 2D 3x3 z wartościami od 1 do 9

In [10]:
######################################################################################

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ustaw ziarno wartości losowej na 5

Wygeneruj wartość losową z zakresu 0 - 1

In [15]:
######################################################################################

0.22199317108973948

Stwórz tablicę 10 elementów z wartościami losowymi

In [17]:
######################################################################################

array([0.7384403 , 0.44130922, 0.15830987, 0.87993703, 0.27408646,
       0.41423502, 0.29607993, 0.62878791, 0.57983781, 0.5999292 ])

Tworzenie tablicy arr potrzebnej do kolejnych poleceń

In [21]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Wyświetl rząd tablicy arr z indexem 3

In [22]:
######################################################################################

array([16, 17, 18, 19, 20])

Wyświetl rzędy tablicy arr z index z zakresu od 0 do 3

In [24]:
######################################################################################

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Wyświetl element z tablicy arr o indexie 2,1

In [26]:
######################################################################################

12

Wyświetl sumę elementów w tablicy arr

In [27]:
######################################################################################

325

Wyświetl elementy większe od 10 z tablicy arr

In [31]:
######################################################################################

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])