In [40]:
print("Hello world!!")

Hello world!!


In [41]:
print("Hello world!")

Hello world!


### Import biblioteki Numpy

In [42]:
import numpy as np

### Pierwsze tablice NumPy

Tablica 1D

In [43]:
arr1D = np.array([1, 2, 3])
arr1D

array([1, 2, 3])

In [44]:
type(arr1D)

numpy.ndarray

Tablica 2D

In [45]:
arr2d = np.array([[1, 2], [3, 4]])
arr2d

array([[1, 2],
       [3, 4]])

Tablica 3D

In [46]:
arr3d = np.array([[[1, 2], [2, 3]], [[4, 5], [6, 7]]])
arr3d

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Wymiary tablic

In [47]:
arr1D.ndim

1

In [48]:
arr2d.ndim

2

In [49]:
arr3d.ndim

3

Kształty tablicy

In [50]:
arr1D.shape

(3,)

In [51]:
arr2d.shape

(2, 2)

In [52]:
arr3d.shape

(2, 2, 2)

Typy danych

In [53]:
arr1D.dtype

dtype('int32')

In [54]:
arr_float = np.array([1.1, 2.9])
arr_float

array([1.1, 2.9])

In [55]:
arr_float.dtype

dtype('float64')

In [56]:
arr_bool = np.array([True, False])
arr_bool

array([ True, False])

In [57]:
arr_bool.dtype

dtype('bool')

In [58]:
arr_int = np.array([1.5, 2.4], dtype='int')  # rzutowanie wartości na wartości dziesiętne
arr_int

array([1, 2])

In [59]:
arr_int.dtype  # dtype sprawdzenie typu, czy jest int czy float czy bool

dtype('int32')

### Funkcje tworzące tablice

In [60]:
np.arange(1, 10)  # tworzy tablice w zakresie od 1 do 10 przedział otwarty a więc bez 10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
np.arange(1, 20, 3)  # tworzenie tablicy z krokiem 3

array([ 1,  4,  7, 10, 13, 16, 19])

In [63]:
np.zeros(3)  # macierz zerowa, czyli z samymi zerami

array([0., 0., 0.])

In [64]:
np.zeros([2, 3])  # 2D dwa wierszy i trzy kolumny

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.ones([2, 3])  # macierz jednostkowa

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [67]:
np.linspace(0, 10, 50)  # podział przedziału 0 do 10 na odpowiedni krok czyli 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [68]:
np.full([2, 2], 3)  # tablica 2 na 2 z wypełnieniem 3

array([[3, 3],
       [3, 3]])

### Podstawowe operacje na tablicach

In [69]:
a = np.array([3, 4, 5, 6])
b = np.array([-1, 2, 4, 1])

In [70]:
print(a)
print(b)

[3 4 5 6]
[-1  2  4  1]


In [71]:
a + b  # dodawanie poszczególnych elementów

array([2, 6, 9, 7])

In [72]:
a - b#%%
print("Hello world!!")

Hello world!!


In [73]:
print("Hello world!")

Hello world!


### Import biblioteki Numpy

In [74]:
import numpy as np

### Pierwsze tablice NumPy

Tablica 1D

In [75]:
arr1D = np.array([1, 2, 3])
arr1D

array([1, 2, 3])

In [76]:
type(arr1D)

numpy.ndarray

Tablica 2D

In [77]:
arr2d = np.array([[1, 2], [3, 4]])
arr2d

array([[1, 2],
       [3, 4]])

Tablica 3D

In [78]:
arr3d = np.array([[[1, 2], [2, 3]], [[4, 5], [6, 7]]])
arr3d

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Wymiary tablic

In [79]:
arr1D.ndim

1

In [80]:
arr2d.ndim

2

In [81]:
arr3d.ndim

3

Kształty tablicy

In [82]:
arr1D.shape

(3,)

In [83]:
arr2d.shape

(2, 2)

In [84]:
arr3d.shape

(2, 2, 2)

Typy danych

In [85]:
arr1D.dtype

dtype('int32')

In [86]:
arr_float = np.array([1.1, 2.9])
arr_float

array([1.1, 2.9])

In [87]:
arr_float.dtype

dtype('float64')

In [88]:
arr_bool = np.array([True, False])
arr_bool

array([ True, False])

In [89]:
arr_bool.dtype

dtype('bool')

In [90]:
arr_int = np.array([1.5, 2.4], dtype='int')  # rzutowanie wartości na wartości dziesiętne
arr_int

array([1, 2])

In [91]:
arr_int.dtype  # dtype sprawdzenie typu, czy jest int czy float czy bool

dtype('int32')

### Funkcje tworzące tablice

In [92]:
np.arange(1, 10)  # tworzy tablice w zakresie od 1 do 10 przedział otwarty a więc bez 10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
np.arange(1, 20, 3)  # tworzenie tablicy z krokiem 3

array([ 1,  4,  7, 10, 13, 16, 19])

In [95]:
np.zeros(3)  # macierz zerowa, czyli z samymi zerami

array([0., 0., 0.])

In [96]:
np.zeros([2, 3])  # 2D dwa wierszy i trzy kolumny

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.ones([2, 3])  # macierz jednostkowa

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [99]:
np.linspace(0, 10, 50)  # podział przedziału 0 do 10 na odpowiedni krok czyli 50

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [100]:
np.full([2, 2], 3)  # tablica 2 na 2 z wypełnieniem 3

array([[3, 3],
       [3, 3]])

### Podstawowe operacje na tablicach

In [101]:
a = np.array([3, 4, 5, 6])
b = np.array([-1, 2, 4, 1])

In [102]:
print(a)
print(b)

[3 4 5 6]
[-1  2  4  1]


In [103]:
a + b  # dodawanie poszczególnych elementów

array([2, 6, 9, 7])

In [104]:
a - b

array([4, 2, 1, 5])

In [105]:
a*b


array([-3,  8, 20,  6])

In [106]:
a+1

array([4, 5, 6, 7])

### Generowanie liczb pseudolosowych

In [108]:
np.random.seed(5) #ustawienie ziarna

In [111]:
np.random.randn() # rozkład normalny

2.43077118700778

In [110]:
np.random.rand() #od zera do jeden

0.8707323061773764

In [112]:
np.random.randn(10)

array([-0.25209213,  0.10960984,  1.58248112, -0.9092324 , -0.59163666,
        0.18760323, -0.32986996, -1.19276461, -0.20487651, -0.35882895])

In [113]:
np.random.randint(10,20)

12

In [114]:
np.random.choice(['a', 'b','c','d'])

'c'