In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Wybór elementu po indeksie

In [3]:
arr[2]

3

In [5]:
arr[2:5] # wybór liczb z zakresu indeksów

array([3, 4, 5])

In [6]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

Przypisywanie nowej wartości

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
arr[0] = 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [11]:
arr[10:12] = 200 #przypisanie nowych wartości do pozycji 10 i 11
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200, 200,  13,
        14,  15])

Zmiana kształtu

In [14]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
arr2d = arr.reshape([3,5]) # zamiana jedno wymiarowej na 2d 5 kol 3 w
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Maski logiczne

In [18]:
arr_rnd = np.random.randn(3,5)
arr_rnd

array([[-0.22419542,  0.68812624, -1.58619771,  0.11868511, -0.04235307],
       [ 0.65669336,  0.2095531 , -0.02720803, -2.27625983, -1.12714574],
       [ 0.57592982, -1.67620333, -0.50193699, -0.6024278 , -0.06352758]])

In [19]:
arr_bool = arr_rnd > 0 # te które są wieksze od zera do true
arr_bool

array([[False,  True, False,  True, False],
       [ True,  True, False, False, False],
       [ True, False, False, False, False]])

In [20]:
arr_rnd[arr_bool] # fitrowanie

array([0.68812624, 0.11868511, 0.65669336, 0.2095531 , 0.57592982])

In [21]:
arr_rnd[arr_rnd>0] # filtrowanie z maska na wartosci wieksze od zera

array([0.68812624, 0.11868511, 0.65669336, 0.2095531 , 0.57592982])

In [22]:
arr_rnd[arr_rnd<0]

array([-0.22419542, -1.58619771, -0.04235307, -0.02720803, -2.27625983,
       -1.12714574, -1.67620333, -0.50193699, -0.6024278 , -0.06352758])